export const mathQuizzes = {
  addition: {
    one: [
      { question: "1 + 0", answer: "1" },
      { question: "1 + 1", answer: "2" },
      { question: "1 + 2", answer: "3" },
      { question: "1 + 3", answer: "4" },
      { question: "1 + 4", answer: "5" },
      { question: "1 + 5", answer: "6" },
      { question: "1 + 6", answer: "7" },
      { question: "1 + 7", answer: "8" },
      { question: "1 + 8", answer: "9" },
      { question: "1 + 9", answer: "10" },
      { question: "1 + 10", answer: "11" },
      { question: "1 + 11", answer: "12" },
      { question: "1 + 12", answer: "13" }
    ],
    two: [
      { question: "2 + 0", answer: "2" },
      { question: "2 + 1", answer: "3" },
      { question: "2 + 2", answer: "4" },
      { question: "2 + 3", answer: "5" },
      { question: "2 + 4", answer: "6" },
      { question: "2 + 5", answer: "7" },
      { question: "2 + 6", answer: "8" },
      { question: "2 + 7", answer: "9" },
      { question: "2 + 8", answer: "10" },
      { question: "2 + 9", answer: "11" },
      { question: "2 + 10", answer: "12" },
      { question: "2 + 11", answer: "13" },
      { question: "2 + 12", answer: "14" }
    ],
    three: [
      { question: "3 + 0", answer: "3" },
      { question: "3 + 1", answer: "4" },
      { question: "3 + 2", answer: "5" },
      { question: "3 + 3", answer: "6" },
      { question: "3 + 4", answer: "7" },
      { question: "3 + 5", answer: "8" },
      { question: "3 + 6", answer: "9" },
      { question: "3 + 7", answer: "10" },
      { question: "3 + 8", answer: "11" },
      { question: "3 + 9", answer: "12" },
      { question: "3 + 10", answer: "13" },
      { question: "3 + 11", answer: "14" },
      { question: "3 + 12", answer: "15" }
    ],
    four: [
      { question: "4 + 0", answer: "4" },
      { question: "4 + 1", answer: "5" },
      { question: "4 + 2", answer: "6" },
      { question: "4 + 3", answer: "7" },
      { question: "4 + 4", answer: "8" },
      { question: "4 + 5", answer: "9" },
      { question: "4 + 6", answer: "10" },
      { question: "4 + 7", answer: "11" },
      { question: "4 + 8", answer: "12" },
      { question: "4 + 9", answer: "13" },
      { question: "4 + 10", answer: "14" },
      { question: "4 + 11", answer: "15" },
      { question: "4 + 12", answer: "16" }
    ],
    five: [
      { question: "5 + 0", answer: "5" },
      { question: "5 + 1", answer: "6" },
      { question: "5 + 2", answer: "7" },
      { question: "5 + 3", answer: "8" },
      { question: "5 + 4", answer: "9" },
      { question: "5 + 5", answer: "10" },
      { question: "5 + 6", answer: "11" },
      { question: "5 + 7", answer: "12" },
      { question: "5 + 8", answer: "13" },
      { question: "5 + 9", answer: "14" },
      { question: "5 + 10", answer: "15" },
      { question: "5 + 11", answer: "16" },
      { question: "5 + 12", answer: "17" }
    ],
    six: [
      { question: "6 + 0", answer: "6" },
      { question: "6 + 1", answer: "7" },
      { question: "6 + 2", answer: "8" },
      { question: "6 + 3", answer: "9" },
      { question: "6 + 4", answer: "10" },
      { question: "6 + 5", answer: "11" },
      { question: "6 + 6", answer: "12" },
      { question: "6 + 7", answer: "13" },
      { question: "6 + 8", answer: "14" },
      { question: "6 + 9", answer: "15" },
      { question: "6 + 10", answer: "16" },
      { question: "6 + 11", answer: "17" },
      { question: "6 + 12", answer: "18" }
    ],
    seven: [
      { question: "7 + 0", answer: "7" },
      { question: "7 + 1", answer: "8" },
      { question: "7 + 2", answer: "9" },
      { question: "7 + 3", answer: "10" },
      { question: "7 + 4", answer: "11" },
      { question: "7 + 5", answer: "12" },
      { question: "7 + 6", answer: "13" },
      { question: "7 + 7", answer: "14" },
      { question: "7 + 8", answer: "15" },
      { question: "7 + 9", answer: "16" },
      { question: "7 + 10", answer: "17" },
      { question: "7 + 11", answer: "18" },
      { question: "7 + 12", answer: "19" }
    ],
    eight: [
      { question: "8 + 0", answer: "8" },
      { question: "8 + 1", answer: "9" },
      { question: "8 + 2", answer: "10" },
      { question: "8 + 3", answer: "11" },
      { question: "8 + 4", answer: "12" },
      { question: "8 + 5", answer: "13" },
      { question: "8 + 6", answer: "14" },
      { question: "8 + 7", answer: "15" },
      { question: "8 + 8", answer: "16" },
      { question: "8 + 9", answer: "17" },
      { question: "8 + 10", answer: "18" },
      { question: "8 + 11", answer: "19" },
      { question: "8 + 12", answer: "20" }
    ],
    nine: [
      { question: "9 + 0", answer: "9" },
      { question: "9 + 1", answer: "10" },
      { question: "9 + 2", answer: "11" },
      { question: "9 + 3", answer: "12" },
      { question: "9 + 4", answer: "13" },
      { question: "9 + 5", answer: "14" },
      { question: "9 + 6", answer: "15" },
      { question: "9 + 7", answer: "16" },
      { question: "9 + 8", answer: "17" },
      { question: "9 + 9", answer: "18" },
      { question: "9 + 10", answer: "19" },
      { question: "9 + 11", answer: "20" },
      { question: "9 + 12", answer: "21" }
    ],
    ten: [
      { question: "10 + 0", answer: "10" },
      { question: "10 + 1", answer: "11" },
      { question: "10 + 2", answer: "12" },
      { question: "10 + 3", answer: "13" },
      { question: "10 + 4", answer: "14" },
      { question: "10 + 5", answer: "15" },
      { question: "10 + 6", answer: "16" },
      { question: "10 + 7", answer: "17" },
      { question: "10 + 8", answer: "18" },
      { question: "10 + 9", answer: "19" },
      { question: "10 + 10", answer: "20" },
      { question: "10 + 11", answer: "21" },
      { question: "10 + 12", answer: "22" }
    ],
    eleven: [
      { question: "11 + 0", answer: "11" },
      { question: "11 + 1", answer: "12" },
      { question: "11 + 2", answer: "13" },
      { question: "11 + 3", answer: "14" },
      { question: "11 + 4", answer: "15" },
      { question: "11 + 5", answer: "16" },
      { question: "11 + 6", answer: "17" },
      { question: "11 + 7", answer: "18" },
      { question: "11 + 8", answer: "19" },
      { question: "11 + 9", answer: "20" },
      { question: "11 + 10", answer: "21" },
      { question: "11 + 11", answer: "22" },
      { question: "11 + 12", answer: "23" }
    ],
    twelve: [
      { question: "12 + 0", answer: "12" },
      { question: "12 + 1", answer: "13" },
      { question: "12 + 2", answer: "14" },
      { question: "12 + 3", answer: "15" },
      { question: "12 + 4", answer: "16" },
      { question: "12 + 5", answer: "17" },
      { question: "12 + 6", answer: "18" },
      { question: "12 + 7", answer: "19" },
      { question: "12 + 8", answer: "20" },
      { question: "12 + 9", answer: "21" },
      { question: "12 + 10", answer: "22" },
      { question: "12 + 11", answer: "23" },
      { question: "12 + 12", answer: "24" }
    ]
  },
  subtraction: {
    one: [
      { question: "1 - 1", answer: "0" },
      { question: "2 - 1", answer: "1" },
      { question: "3 - 1", answer: "2" },
      { question: "4 - 1", answer: "3" },
      { question: "5 - 1", answer: "4" },
      { question: "6 - 1", answer: "5" },
      { question: "7 - 1", answer: "6" },
      { question: "8 - 1", answer: "7" },
      { question: "9 - 1", answer: "8" },
      { question: "10 - 1", answer: "9" },
      { question: "11 - 1", answer: "10" },
      { question: "12 - 1", answer: "11" }
    ],
    two: [
      { question: "2 - 2", answer: "0" },
      { question: "3 - 2", answer: "1" },
      { question: "4 - 2", answer: "2" },
      { question: "5 - 2", answer: "3" },
      { question: "6 - 2", answer: "4" },
      { question: "7 - 2", answer: "5" },
      { question: "8 - 2", answer: "6" },
      { question: "9 - 2", answer: "7" },
      { question: "10 - 2", answer: "8" },
      { question: "11 - 2", answer: "9" },
      { question: "12 - 2", answer: "10" },
      { question: "13 - 2", answer: "11" }
    ],
    three: [
      { question: "3 - 3", answer: "0" },
      { question: "4 - 3", answer: "1" },
      { question: "5 - 3", answer: "2" },
      { question: "6 - 3", answer: "3" },
      { question: "7 - 3", answer: "4" },
      { question: "8 - 3", answer: "5" },
      { question: "9 - 3", answer: "6" },
      { question: "10 - 3", answer: "7" },
      { question: "11 - 3", answer: "8" },
      { question: "12 - 3", answer: "9" },
      { question: "13 - 3", answer: "10" },
      { question: "14 - 3", answer: "11" },
      { question: "15 - 3", answer: "13" },
    ],
    four: [
      { question: "4 - 4", answer: "0" },
      { question: "5 - 4", answer: "1" },
      { question: "6 - 4", answer: "2" },
      { question: "7 - 4", answer: "3" },
      { question: "8 - 4", answer: "4" },
      { question: "9 - 4", answer: "5" },
      { question: "10 - 4", answer: "6" },
      { question: "11 - 4", answer: "7" },
      { question: "12 - 4", answer: "8" },
      { question: "13 - 4", answer: "9" },
      { question: "14 - 4", answer: "10" },
      { question: "15 - 4", answer: "11" },
      { question: "16 - 4", answer: "12" }
    ],
    five: [
      { question: "5 - 5", answer: "0" },
      { question: "6 - 5", answer: "1" },
      { question: "7 - 5", answer: "2" },
      { question: "8 - 5", answer: "3" },
      { question: "9 - 5", answer: "4" },
      { question: "10 - 5", answer: "5" },
      { question: "11 - 5", answer: "6" },
      { question: "12 - 5", answer: "7" },
      { question: "13 - 5", answer: "8" },
      { question: "14 - 5", answer: "9" },
      { question: "15 - 5", answer: "10" },
      { question: "16 - 5", answer: "11" },
      { question: "17 - 5", answer: "12" }
    ],
    six: [
      { question: "6 - 6", answer: "0" },
      { question: "7 - 6", answer: "1" },
      { question: "8 - 6", answer: "2" },
      { question: "9 - 6", answer: "3" },
      { question: "10 - 6", answer: "4" },
      { question: "11 - 6", answer: "5" },
      { question: "12 - 6", answer: "6" },
      { question: "13 - 6", answer: "7" },
      { question: "14 - 6", answer: "8" },
      { question: "15 - 6", answer: "9" },
      { question: "16 - 6", answer: "10" },
      { question: "17 - 6", answer: "11" },
      { question: "18 - 6", answer: "12" }
    ],
    seven: [
      { question: "7 - 7", answer: "0" },
      { question: "8 - 7", answer: "1" },
      { question: "9 - 7", answer: "2" },
      { question: "10 - 7", answer: "3" },
      { question: "11 - 7", answer: "4" },
      { question: "12 - 7", answer: "5" },
      { question: "13 - 7", answer: "6" },
      { question: "14 - 7", answer: "7" },
      { question: "15 - 7", answer: "8" },
      { question: "16 - 7", answer: "9" },
      { question: "17 - 7", answer: "10" },
      { question: "18 - 7", answer: "11" },
      { question: "19 - 7", answer: "12" }
    ],
    eight: [
      { question: "8 - 8", answer: "0" },
      { question: "9 - 8", answer: "1" },
      { question: "10 - 8", answer: "2" },
      { question: "11 - 8", answer: "3" },
      { question: "12 - 8", answer: "4" },
      { question: "13 - 8", answer: "5" },
      { question: "14 - 8", answer: "6" },
      { question: "15 - 8", answer: "7" },
      { question: "16 - 8", answer: "8" },
      { question: "17 - 8", answer: "9" },
      { question: "18 - 8", answer: "10" },
      { question: "18 - 8", answer: "11" },
      { question: "20 - 8", answer: "12" }
    ],
    nine: [
      { question: "9 - 9", answer: "0" },
      { question: "10 - 9", answer: "1" },
      { question: "11 - 9", answer: "2" },
      { question: "12 - 9", answer: "3" },
      { question: "13 - 9", answer: "4" },
      { question: "14 - 9", answer: "5" },
      { question: "15 - 9", answer: "6" },
      { question: "16 - 9", answer: "7" },
      { question: "17 - 9", answer: "8" },
      { question: "18 - 9", answer: "9" },
      { question: "19 - 9", answer: "10" },
      { question: "20 - 9", answer: "11" },
      { question: "21 - 9", answer: "12" },
    ],
    ten: [
      { question: "10 - 10", answer: "0" },
      { question: "11 - 10", answer: "1" },
      { question: "12 - 10", answer: "2" },
      { question: "13 - 10", answer: "3" },
      { question: "14 - 10", answer: "4" },
      { question: "15 - 10", answer: "5" },
      { question: "16 - 10", answer: "6" },
      { question: "17 - 10", answer: "7" },
      { question: "18 - 10", answer: "8" },
      { question: "19 - 10", answer: "9" },
      { question: "20 - 10", answer: "10" },
      { question: "21 - 10", answer: "11" },
      { question: "22 - 10", answer: "12" }
    ],
    eleven: [
      { question: "11 - 11", answer: "0" },
      { question: "12 - 11", answer: "1" },
      { question: "13 - 11", answer: "2" },
      { question: "14 - 11", answer: "3" },
      { question: "15 - 11", answer: "4" },
      { question: "16 - 11", answer: "5" },
      { question: "17 - 11", answer: "6" },
      { question: "18 - 11", answer: "7" },
      { question: "19 - 11", answer: "8" },
      { question: "20 - 11", answer: "9" },
      { question: "21 - 11", answer: "10" },
      { question: "22 - 11", answer: "11" },
      { question: "23 - 11", answer: "12" }
    ],
    twelve: [
      { question: "12 - 12", answer: "0" },
      { question: "13 - 12", answer: "1" },
      { question: "14 - 12", answer: "2" },
      { question: "15 - 12", answer: "3" },
      { question: "16 - 12", answer: "4" },
      { question: "17 - 12", answer: "5" },
      { question: "18 - 12", answer: "6" },
      { question: "19 - 12", answer: "7" },
      { question: "20 - 12", answer: "8" },
      { question: "21 - 12", answer: "9" },
      { question: "22 - 12", answer: "10" },
      { question: "23 - 12", answer: "11" },
      { question: "24 - 12", answer: "12" }
    ]
  },
  multiplication: {
    one: [
      { question: "1 * 0", answer: "0" },
      { question: "1 * 1", answer: "1" },
      { question: "1 * 2", answer: "2" },
      { question: "1 * 3", answer: "3" },
      { question: "1 * 4", answer: "4" },
      { question: "1 * 5", answer: "5" },
      { question: "1 * 6", answer: "6" },
      { question: "1 * 7", answer: "7" },
      { question: "1 * 8", answer: "8" },
      { question: "1 * 9", answer: "9" },
      { question: "1 * 10", answer: "10" },
      { question: "1 * 11", answer: "11" },
      { question: "1 * 12", answer: "12" }
    ],
    two: [
      { question: "2 * 0", answer: "0" },
      { question: "2 * 1", answer: "2" },
      { question: "2 * 2", answer: "4" },
      { question: "2 * 3", answer: "6" },
      { question: "2 * 4", answer: "8" },
      { question: "2 * 5", answer: "10" },
      { question: "2 * 6", answer: "12" },
      { question: "2 * 7", answer: "14" },
      { question: "2 * 8", answer: "16" },
      { question: "2 * 9", answer: "18" },
      { question: "2 * 10", answer: "20" },
      { question: "2 * 11", answer: "22" },
      { question: "2 * 12", answer: "24" }
    ],
    three: [
      { question: "3 * 0", answer: "0" },
      { question: "3 * 1", answer: "3" },
      { question: "3 * 2", answer: "6" },
      { question: "3 * 3", answer: "9" },
      { question: "3 * 4", answer: "12" },
      { question: "3 * 5", answer: "15" },
      { question: "3 * 6", answer: "18" },
      { question: "3 * 7", answer: "21" },
      { question: "3 * 8", answer: "24" },
      { question: "3 * 9", answer: "27" },
      { question: "3 * 10", answer: "30" },
      { question: "3 * 11", answer: "33" },
      { question: "3 * 12", answer: "36" }
    ],
    four: [
      { question: "4 * 0", answer: "0" },
      { question: "4 * 1", answer: "4" },
      { question: "4 * 2", answer: "8" },
      { question: "4 * 3", answer: "12" },
      { question: "4 * 4", answer: "16" },
      { question: "4 * 5", answer: "20" },
      { question: "4 * 6", answer: "24" },
      { question: "4 * 7", answer: "28" },
      { question: "4 * 8", answer: "32" },
      { question: "4 * 9", answer: "36" },
      { question: "4 * 10", answer: "40" },
      { question: "4 * 11", answer: "44" },
      { question: "4 * 12", answer: "48" }
    ],
    five: [
      { question: "5 * 0", answer: "0" },
      { question: "5 * 1", answer: "5" },
      { question: "5 * 2", answer: "10" },
      { question: "5 * 3", answer: "15" },
      { question: "5 * 4", answer: "20" },
      { question: "5 * 5", answer: "25" },
      { question: "5 * 6", answer: "30" },
      { question: "5 * 7", answer: "35" },
      { question: "5 * 8", answer: "40" },
      { question: "5 * 9", answer: "45" },
      { question: "5 * 10", answer: "50" },
      { question: "5 * 11", answer: "55" },
      { question: "5 * 12", answer: "60" }
    ],
    six: [
      { question: "6 * 0", answer: "0" },
      { question: "6 * 1", answer: "6" },
      { question: "6 * 2", answer: "12" },
      { question: "6 * 3", answer: "18" },
      { question: "6 * 4", answer: "24" },
      { question: "6 * 5", answer: "30" },
      { question: "6 * 6", answer: "36" },
      { question: "6 * 7", answer: "42" },
      { question: "6 * 8", answer: "48" },
      { question: "6 * 9", answer: "54" },
      { question: "6 * 10", answer: "60" },
      { question: "6 * 11", answer: "66" },
      { question: "6 * 12", answer: "72" }
    ],
    seven: [
      { question: "7 * 0", answer: "0" },
      { question: "7 * 1", answer: "7" },
      { question: "7 * 2", answer: "14" },
      { question: "7 * 3", answer: "21" },
      { question: "7 * 4", answer: "28" },
      { question: "7 * 5", answer: "35" },
      { question: "7 * 6", answer: "42" },
      { question: "7 * 7", answer: "49" },
      { question: "7 * 8", answer: "56" },
      { question: "7 * 9", answer: "63" },
      { question: "7 * 10", answer: "70" },
      { question: "7 * 11", answer: "77" },
      { question: "7 * 12", answer: "84" }
    ],
    eight: [
      { question: "8 * 0", answer: "0" },
      { question: "8 * 1", answer: "8" },
      { question: "8 * 2", answer: "16" },
      { question: "8 * 3", answer: "24" },
      { question: "8 * 4", answer: "32" },
      { question: "8 * 5", answer: "40" },
      { question: "8 * 6", answer: "48" },
      { question: "8 * 7", answer: "56" },
      { question: "8 * 8", answer: "64" },
      { question: "8 * 9", answer: "72" },
      { question: "8 * 10", answer: "80" },
      { question: "8 * 11", answer: "88" },
      { question: "8 * 12", answer: "96" }
    ],
    nine: [
      { question: "9 * 0", answer: "0" },
      { question: "9 * 1", answer: "9" },
      { question: "9 * 2", answer: "18" },
      { question: "9 * 3", answer: "27" },
      { question: "9 * 4", answer: "36" },
      { question: "9 * 5", answer: "45" },
      { question: "9 * 6", answer: "54" },
      { question: "9 * 7", answer: "63" },
      { question: "9 * 8", answer: "72" },
      { question: "9 * 9", answer: "81" },
      { question: "9 * 10", answer: "90" },
      { question: "9 * 11", answer: "99" },
      { question: "9 * 12", answer: "108" }
    ],
    ten: [
      { question: "10 * 0", answer: "0" },
      { question: "10 * 1", answer: "10" },
      { question: "10 * 2", answer: "20" },
      { question: "10 * 3", answer: "30" },
      { question: "10 * 4", answer: "40" },
      { question: "10 * 5", answer: "50" },
      { question: "10 * 6", answer: "60" },
      { question: "10 * 7", answer: "70" },
      { question: "10 * 8", answer: "80" },
      { question: "10 * 9", answer: "90" },
      { question: "10 * 10", answer: "100" },
      { question: "10 * 11", answer: "110" },
      { question: "10 * 12", answer: "120" }
    ],
    eleven: [
      { question: "11 * 0", answer: "0" },
      { question: "11 * 1", answer: "11" },
      { question: "11 * 2", answer: "22" },
      { question: "11 * 3", answer: "33" },
      { question: "11 * 4", answer: "44" },
      { question: "11 * 5", answer: "55" },
      { question: "11 * 6", answer: "66" },
      { question: "11 * 7", answer: "77" },
      { question: "11 * 8", answer: "88" },
      { question: "11 * 9", answer: "99" },
      { question: "11 * 10", answer: "110" },
      { question: "11 * 11", answer: "121" },
      { question: "11 * 12", answer: "132" }
    ],
    twelve: [
      { question: "12 * 0", answer: "0" },
      { question: "12 * 1", answer: "12" },
      { question: "12 * 2", answer: "24" },
      { question: "12 * 3", answer: "36" },
      { question: "12 * 4", answer: "48" },
      { question: "12 * 5", answer: "60" },
      { question: "12 * 6", answer: "72" },
      { question: "12 * 7", answer: "84" },
      { question: "12 * 8", answer: "96" },
      { question: "12 * 9", answer: "108" },
      { question: "12 * 10", answer: "120" },
      { question: "12 * 11", answer: "132" },
      { question: "12 * 12", answer: "144" }
    ]
  },
  division: {
    one: [
      { question: "0 / 1", answer: "0" },
      { question: "1 / 1", answer: "1" },
      { question: "2 / 1", answer: "2" },
      { question: "3 / 1", answer: "3" },
      { question: "4 / 1", answer: "4" },
      { question: "5 / 1", answer: "5" },
      { question: "6 / 1", answer: "6" },
      { question: "7 / 1", answer: "7" },
      { question: "8 / 1", answer: "8" },
      { question: "9 / 1", answer: "9" },
      { question: "10 / 1", answer: "10" },
      { question: "11 / 1", answer: "11" },
      { question: "12 / 1", answer: "12" }
    ],
    two: [
      { question: "0 / 2", answer: "0" },
      { question: "2 / 2", answer: "1" },
      { question: "4 / 2", answer: "2" },
      { question: "6 / 2", answer: "3" },
      { question: "8 / 2", answer: "4" },
      { question: "10 / 2", answer: "5" },
      { question: "12 / 2", answer: "6" },
      { question: "14 / 2", answer: "7" },
      { question: "16 / 2", answer: "8" },
      { question: "18 / 2", answer: "9" },
      { question: "20 / 2", answer: "10" },
      { question: "22 / 2", answer: "11" },
      { question: "24 / 2", answer: "12" }
    ],
    three: [
      { question: "0 / 3", answer: "0" },
      { question: "3 / 3", answer: "1" },
      { question: "6 / 3", answer: "2" },
      { question: "9 / 3", answer: "3" },
      { question: "12 / 3", answer: "4" },
      { question: "15 / 3", answer: "5" },
      { question: "18 / 3", answer: "6" },
      { question: "21 / 3", answer: "7" },
      { question: "24 / 3", answer: "8" },
      { question: "27 / 3", answer: "9" },
      { question: "30 / 3", answer: "10" },
      { question: "33 / 3", answer: "11" },
      { question: "36 / 3", answer: "12" }
    ],
    four: [
      { question: "0 / 4", answer: "0" },
      { question: "4 / 4", answer: "1" },
      { question: "8 / 4", answer: "2" },
      { question: "12 / 4", answer: "3" },
      { question: "16 / 4", answer: "4" },
      { question: "20 / 4", answer: "5" },
      { question: "24 / 4", answer: "6" },
      { question: "28 / 4", answer: "7" },
      { question: "32 / 4", answer: "8" },
      { question: "36 / 4", answer: "9" },
      { question: "40 / 4", answer: "10" },
      { question: "44 / 4", answer: "11" },
      { question: "48 / 4", answer: "12" }
    ],
    five: [
      { question: "0 / 5", answer: "0" },
      { question: "5 / 5", answer: "1" },
      { question: "10 / 5", answer: "2" },
      { question: "15 / 5", answer: "3" },
      { question: "20 / 5", answer: "4" },
      { question: "25 / 5", answer: "5" },
      { question: "30 / 5", answer: "6" },
      { question: "35 / 5", answer: "7" },
      { question: "40 / 5", answer: "8" },
      { question: "45 / 5", answer: "9" },
      { question: "50 / 5", answer: "10" },
      { question: "55 / 5", answer: "11" },
      { question: "60 / 5", answer: "12" }
    ],
    six: [
      { question: "0 / 6", answer: "0" },
      { question: "6 / 6", answer: "1" },
      { question: "12 / 6", answer: "2" },
      { question: "18 / 6", answer: "3" },
      { question: "24 / 6", answer: "4" },
      { question: "30 / 6", answer: "5" },
      { question: "36 / 6", answer: "6" },
      { question: "42 / 6", answer: "7" },
      { question: "48 / 6", answer: "8" },
      { question: "54 / 6", answer: "9" },
      { question: "60 / 6", answer: "10" },
      { question: "66 / 6", answer: "11" },
      { question: "72 / 6", answer: "12" }
    ],
    seven: [
      { question: "0 / 7", answer: "0" },
      { question: "7 / 7", answer: "1" },
      { question: "14 / 7", answer: "2" },
      { question: "21 / 7", answer: "3" },
      { question: "28 / 7", answer: "4" },
      { question: "35 / 7", answer: "5" },
      { question: "42 / 7", answer: "6" },
      { question: "49 / 7", answer: "7" },
      { question: "56 / 7", answer: "8" },
      { question: "63 / 7", answer: "9" },
      { question: "70 / 7", answer: "10" },
      { question: "77 / 7", answer: "11" },
      { question: "84 / 7", answer: "12" }
    ],
    eight: [
      { question: "0 / 8", answer: "0" },
      { question: "8 / 8", answer: "1" },
      { question: "16 / 8", answer: "2" },
      { question: "24 / 8", answer: "3" },
      { question: "32 / 8", answer: "4" },
      { question: "40 / 8", answer: "5" },
      { question: "48 / 8", answer: "6" },
      { question: "56 / 8", answer: "7" },
      { question: "64 / 8", answer: "8" },
      { question: "72 / 8", answer: "9" },
      { question: "80 / 8", answer: "10" },
      { question: "88 / 8", answer: "11" },
      { question: "96 / 8", answer: "12" }
    ],
    nine: [
      { question: "0 / 9", answer: "0" },
      { question: "9 / 9", answer: "1" },
      { question: "18 / 9", answer: "2" },
      { question: "27 / 9", answer: "3" },
      { question: "36 / 9", answer: "4" },
      { question: "45 / 9", answer: "5" },
      { question: "54 / 9", answer: "6" },
      { question: "63 / 9", answer: "7" },
      { question: "72 / 9", answer: "8" },
      { question: "81 / 9", answer: "9" },
      { question: "90 / 9", answer: "10" },
      { question: "99 / 9", answer: "11" },
      { question: "108 / 9", answer: "12" }
    ],
    ten: [
      { question: "0 / 10", answer: "0" },
      { question: "10 / 10", answer: "1" },
      { question: "20 / 10", answer: "2" },
      { question: "30 / 10", answer: "3" },
      { question: "40 / 10", answer: "4" },
      { question: "50 / 10", answer: "5" },
      { question: "60 / 10", answer: "6" },
      { question: "70 / 10", answer: "7" },
      { question: "80 / 10", answer: "8" },
      { question: "90 / 10", answer: "9" },
      { question: "100 / 10", answer: "10" },
      { question: "110 / 10", answer: "11" },
      { question: "120 / 10", answer: "12" }
    ],
    eleven: [
      { question: "0 / 11", answer: "0" },
      { question: "11 / 11", answer: "1" },
      { question: "22 / 11", answer: "2" },
      { question: "33 / 11", answer: "3" },
      { question: "44 / 11", answer: "4" },
      { question: "55 / 11", answer: "5" },
      { question: "66 / 11", answer: "6" },
      { question: "77 / 11", answer: "7" },
      { question: "88 / 11", answer: "8" },
      { question: "99 / 11", answer: "9" },
      { question: "110 / 11", answer: "10" },
      { question: "121 / 11", answer: "11" },
      { question: "132 / 11", answer: "12" }
    ],
    twelve: [
      { question: "0 / 12", answer: "0" },
      { question: "12 / 12", answer: "1" },
      { question: "24 / 12", answer: "2" },
      { question: "36 / 12", answer: "3" },
      { question: "48 / 12", answer: "4" },
      { question: "60 / 12", answer: "5" },
      { question: "72 / 12", answer: "6" },
      { question: "84 / 12", answer: "7" },
      { question: "96 / 12", answer: "8" },
      { question: "108 / 12", answer: "9" },
      { question: "120 / 12", answer: "10" },
      { question: "132 / 12", answer: "11" },
      { question: "144 / 12", answer: "12" }
    ]
  }
};


